/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : string,
  'title' : string,
  'content' : string,
  'publishDate' : bigint,
  'tags' : Array<string>,
  'author' : string,
  'imageUrl' : string,
  'excerpt' : string,
}
export interface ContactMessage {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface Order {
  'id' : string,
  'customerName' : string,
  'status' : string,
  'customerPhone' : string,
  'createdAt' : bigint,
  'customerAddress' : string,
  'totalAmount' : number,
  'items' : Array<OrderItem>,
  'customerEmail' : string,
}
export interface OrderItem {
  'productId' : string,
  'productName' : string,
  'quantity' : bigint,
  'price' : number,
}
export interface Product {
  'id' : string,
  'inStock' : boolean,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'price' : number,
}
export interface _SERVICE {
  'addBlogPost' : ActorMethod<[BlogPost], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'deleteBlogPost' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getBlogPostById' : ActorMethod<[string], BlogPost>,
  'getContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getOrderById' : ActorMethod<[string], Order>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'placeOrder' : ActorMethod<[Order], undefined>,
  'submitContactMessage' : ActorMethod<[ContactMessage], undefined>,
  'updateOrderStatus' : ActorMethod<[string, string], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];